### ISSUE TITLE
Major Element in an array in O(n) time complexity

### ISSUE THREAD

**Issue by mansim3006** [abhishekchandra2522k/Java-Programs#3]
An element whose occurrence is more than n/2 where n is the number of elements in an array.
can i raise PR to add this program?

**Comment by abhishekchandra2522k** [comment]
Yes you can raise a Pull Request, but the code should be written in Java Language.

**Comment by mansim3006** [comment]
not able to create a new branch to raise PR. Any suggestions?

**Comment by abhishekchandra2522k** [comment]
![WhatsApp Image 2020-10-29 at 15 50 51](https://user-images.githubusercontent.com/51490584/97555920-c0aec980-19fe-11eb-9c88-f693845e5511.jpeg)
![WhatsApp Image 2020-10-29 at 15 50 12](https://user-images.githubusercontent.com/51490584/97555926-c2788d00-19fe-11eb-8596-402f33cbcce1.jpeg)

I think your issue is solved, you have made two branches in your forked repository, although I have added the images for your clarification.
